language: node_js
node_js: stable
# S: Build Lifecycle
cache:
  directories:
  - node_modules

install:
  - npm install -g hexo-cli
  - npm install hexo-deployer-git --save
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g
  - hexo g
after_script:
  - cd public
  - git init
  - git config user.name "the-sword"
  - git config user.email "xhzhou1991@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GIT_PAGE_REF}" master:master
after_success:
  - hexo deploy  
# E: Build LifeCycle
branches:
  only:
  - hexo
env:
  global:
  - GIT_PAGE_REF: github.com/the-sword/the-sword.github.io.git
  - secure: "VxBbc97YAYnFmj7SyrIW++N+ldsPQ8fdf6SjSEZDiuIu5C7bGGriZIdiah0lOQLoldPbqwFcA+hSnq/hzDL7yumrCPSPKFBA6jcXE7giRmxxALQNbey78JrhH4pidjaPRbghBXWUkvJD1VOy3xkqcwyrTA3C1PKjBf/AIJSdF6tVB3ELHexBmXD709hfugA+tSO7dWs7Yo2g/fec2co/QkU67Eh1ULCaDLCGatd6SYrWvxD4TfetUk991q0Kd3HTGipB4Xwiyi6fD27H0QXWRxuGAM86PjqrlWche3w6FTyVK8bemjmOLKaN9eYSUIrhfXELzYZXCy2P5/SlotJpmCf7lt3TZS4sR5OLc2Ql9+l1uTCspz49zNeL78/99n+lCLuEW0fGlRAjNAMKz4H0tIKki+z0uFzy3b98Kt0/PO9p1wokcGPI1NujzaxzL1sO+K0jeI8EIA6KIu7BCpUuDNjrOIUhaWA5Gmw1UDgsXxNEb4J6ZyXk4QIu2RyjWyZ3iBnOun+ahNzch6ys59imfH3Q6ZdbDBtmYEdpcP6NsQdKchnfJQ1G6yt11sDi1F69t+IFj119z4yJYBTCBPWr/ieAwpLLaazVjx92RiM4USA6sn9oIxKIGp+FPrI7rlByT9pZhw0HNYc7GuNsOkNQ+Gq1AaMh2QKTg4fsLYd//4U="
notifications:
  email:
  - xhzhou1991@gmail.com
  on_success: change
  on_failure: change
